name: Flaky Checks

on:
  pull_request:
  merge_group:

jobs:
  flaky-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show context for debugging
        run: |
          echo "=== Flaky Test Context ==="
          echo "SHA: ${{ github.sha }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Run ID: ${{ github.run_id }}"

      - name: Random failure test (30% failure rate)
        run: |
          RANDOM_NUM=$((RANDOM % 10))
          echo "Random number: $RANDOM_NUM"
          if [ $RANDOM_NUM -lt 3 ]; then
            echo "Test failed randomly!"
            exit 1
          fi
          echo "Test passed!"

  unstable-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Integration test with 50% failure rate
        run: |
          RANDOM_NUM=$((RANDOM % 2))
          echo "Running unstable integration test..."
          sleep 2
          if [ $RANDOM_NUM -eq 0 ]; then
            echo "Integration test failed!"
            exit 1
          fi
          echo "Integration test passed!"

  timing-sensitive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Time-based test (fails during certain minutes)
        run: |
          MINUTE=$(date +%M)
          echo "Current minute: $MINUTE"
          # Fail if minute ends in 3, 6, or 9
          if [[ $MINUTE =~ [369]$ ]]; then
            echo "Test failed due to timing!"
            exit 1
          fi
          echo "Timing test passed!"
