name: Merge Queue CI

on:
  pull_request:
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show SHA information
        run: |
          echo "=== SHA Information ==="
          echo "HEAD SHA: ${{ github.sha }}"
          echo "PR Head SHA: ${{ github.event.pull_request.head.sha || 'N/A' }}"
          echo "PR Base SHA: ${{ github.event.pull_request.base.sha || 'N/A' }}"
          echo "Merge Group Head SHA: ${{ github.event.merge_group.head_sha || 'N/A' }}"
          echo "Merge Group Base SHA: ${{ github.event.merge_group.base_sha || 'N/A' }}"
          echo ""
          echo "=== Git Log (last 5 commits) ==="
          git log --oneline -5
          echo ""
          echo "=== Event Context ==="
          echo "Event Name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"

      - name: Run tests
        run: |
          npm test
          sleep 2
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}

      - name: Create artifact file
        run: |
          echo "foo, this is bar" > artifact.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: artifact.txt

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run linting
        run: |
          echo "Running linter..."
          sleep 1
          echo "Linting completed"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build project
        run: |
          echo "Building project..."
          sleep 3
          echo "Build completed"
