name: On merge group failure

on:
  pull_request:
    types:
      - dequeued

jobs:
  on_merge_group_failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.reason == 'CI_FAILURE' }}
    steps:
      - name: Dump event
        run: |
          echo "Head: ${{ github.event.pull_request.head.sha }}"
          gh api '/repos/one-dark/merge-queue-test/actions/workflows/merge-queue.yml/runs?head_sha=${{ github.event.pull_request.head.sha }}'
        env:
          GH_TOKEN: ${{ github.token }}
