name: On merge group failure

on:
  pull_request:
    types:
      - dequeued

jobs:
  on_merge_group_failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.reason == 'CI_FAILURE' }}
    steps:
      - name: Dump event
        run: |
          echo "Base: ${{ github.event.pull_request.base.sha }}"
          echo "Head: ${{ github.event.pull_request.head.sha }}"
          echo "Merge commit: ${{ github.event.pull_request.merge_commit_sha }}"
