name: On merge group failure

on:
  pull_request:
    types:
      - dequeued

jobs:
  on_merge_group_failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.reason == 'CI_FAILURE' }}
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            console.log(JSON.stringify(context, null, 2));
